const refund = {
  "refund.title": "Refund Policy",
  "refund.subtitle": "Card Train Refund & Return Terms",
  "refund.lastUpdated": "Last Updated: June 16, 2025",
  "refund.toc": "Contents",
  "refund.general": "General Provisions",
  "refund.points": "CardTrain Points Policy",
  "refund.draws": "Draw Prizes",
  "refund.prizes": "Prize Returns",
  "refund.shop": "Shop Orders",
  "refund.method": "Refund Method",
  "refund.exclusions": "Non-Refundable Situations",
  "refund.abuse": "Abuse & Fraud",
  "refund.contact": 'Contact Us',
  "refund.footer": "This Refund Policy is established by Card Train and we reserve the right of final interpretation",
  "refund.sections": [
    {
      "id": "general",
      "title": "General Provisions",
      "content": [
        "This Refund Policy (hereinafter referred to as 'this Policy') applies to the current services provided by Card Train (hereinafter referred to as 'the Platform'), including lucky bag draws, shop purchases, point purchases, and other related transactions.",
        "The Platform is committed to providing users with a fair and transparent online lucky bag experience. All draw results are generated by a system random algorithm and cannot be predicted or manually interfered with. Users should fully understand and accept the random nature of draws before participating."
      ]
    },
    {
      "id": "points",
      "title": "CardTrain Points Policy",
      "content": [
        "CardTrain Points (CTP) are the Platform's exclusive currency for use within the Platform only. They have no cash value, cannot be converted to cash, transferred to third parties, or withdrawn.",
        "Once purchased, CTP is non-refundable. Users are advised to purchase according to their actual needs. If a user's account is suspended, voluntarily deleted, or service is terminated for any reason, any remaining CTP in the account will automatically expire. The Platform will not refund or compensate in any manner.",
        "If a Platform system malfunction causes CTP to be deducted without the draw process being completed (e.g., the transaction record shows a deduction but no draw result), the Platform will, upon administrator verification, replenish the corresponding CTP to the user's account within 3 to 5 business days."
      ]
    },
    {
      "id": "draws",
      "title": "Draw Prizes & Results",
      "content": [
        "Draws are a form of random entertainment. Once a result is generated, it is final. Regardless of whether the user is satisfied with the result, the deducted CTP will not be refunded.",
        "After a draw is completed, the prize will be recorded in the user's 'Draw History'. The user may choose to: (a) apply for shipping to receive the physical prize; or (b) redeem the prize for CTP (if the prize supports redemption). The redemption ratio is determined solely by the Platform and may be adjusted according to market prices.",
        "Users may not request refunds, returns, or transaction reversals on the grounds of 'not winning the target prize', 'the prize\'s market value is lower than expected', or 'dissatisfaction with the result'."
      ]
    },
    {
      "id": "prizes",
      "title": "Prize Returns & Defects",
      "content": [
        "If a prize received by the user has obvious defects, does not match the draw record (e.g., the record shows an A-tier prize but a B-tier was received), or the package was severely damaged causing the prize to be damaged, the user must file a claim via the 'Contact Us' page within 48 hours of receipt, providing clear photos and the tracking number.",
        "Upon administrator verification, the Platform will provide one of the following remedies (at the Platform's sole discretion): (a) re-shipment of the same prize; (b) provision of an equivalent shop item as a substitute; or (c) refund of the equivalent CTP to the user's account based on the prize's market reference price.",
        "The following are not considered defects and are not eligible for return or exchange: (a) minor color variations, cutting differences, or printing offsets due to manufacturing batch variations (within normal factory range); (b) minor wear on packaging materials (such as card sleeves or toploaders); (c) requests due to personal reasons (such as change of collection preference or duplicate acquisition)."
      ]
    },
    {
      "id": "shop",
      "title": "Shop Order Refunds",
      "content": [
        "Once a shop order is confirmed and CTP is deducted, refunds or cancellations are generally not accepted. Users should carefully review product specifications, quantities, and required CTP before placing an order.",
        "If a shop product has serious quality issues (such as a severe discrepancy from the product description, or the product is broken and unusable), the user may file a claim within 7 days of receipt. Upon verification, the Platform will refund the full CTP amount for that product.",
        "Requests to cancel shop orders or request refunds due to personal reasons (such as ordering the wrong item, change of mind, or no longer wanting the item) will not be accepted by the Platform."
      ]
    },
    {
      "id": "method",
      "title": "Refund Method",
      "content": [
        "All refunds from the Platform will be credited to the user's account in the form of CardTrain Points (CTP). No cash refunds, bank transfers, credit card chargebacks, or other forms of refund will be issued.",
        "Refund CTP will be credited within 10 to 14 business days after the administrator completes the review. Users may view refund details in their 'Point History'.",
        "If a user's account has been suspended or deleted due to violations, the refund cannot be processed and the Platform assumes no responsibility for this."
      ]
    },
    {
      "id": "exclusions",
      "title": "Non-Refundable Situations",
      "content": [
        "Except as otherwise provided in this Policy, the following situations are non-refundable or non-compensable:",
        "(a) CTP consumption caused by user operational errors (such as accidentally clicking draw, selecting the wrong bag, or selecting the wrong draw count);",
        "(b) transactions resulting from a user's account being hacked, password leaked, or device being used by another person;",
        "(c) prizes expired due to the user failing to submit a shipping request within the specified time limit;",
        "(d) packages returned, lost, or undeliverable due to incorrect addresses provided by the user;",
        "(e) prizes opened, damaged, or modified by the user, affecting their original condition;",
        "(f) any service interruption or inability to complete transactions due to force majeure (such as natural disasters, war, epidemics, or government bans)."
      ]
    },
    {
      "id": "abuse",
      "title": "Abuse & Fraud Prevention",
      "content": [
        "The Platform strictly prohibits users from attempting to fraudulently obtain refunds, re-shipments, or extra CTP through false claims, forged evidence, or malicious complaints.",
        "If a user is found to be abusing the refund policy, committing fraud, or engaging in abnormal transactions, the Platform reserves the right to immediately suspend or permanently terminate the user's account, and reserves the right to recover any issued prizes, CTP, or take legal action.",
        "The Platform retains final decision-making authority over the interpretation and enforcement of this Refund Policy."
      ]
    },
    {
      "id": "contact",
      "title": 'Contact Us',
      "content": [
        "If you have any questions about this Refund Policy, or believe your transaction qualifies for a refund, please submit a detailed explanation via the 'Contact Us' page, including the relevant transaction number, screenshots, and supporting evidence.",
        "We will review and respond within 10 to 14 business days of receiving your application. To protect the rights of both parties, please retain all transaction records and correspondence."
      ]
    }
  ]
};

export default refund;