const translation = {
  "terms.title": "Terms of Service",
  "terms.subtitle": "Terms of Service",
  "terms.lastUpdated": "Last Updated: January 2024",
  "terms.toc": "Contents",
  "terms.importantNotice": "Important Notice:",
  "terms.importantNoticeDesc": "Please read these Terms of Service carefully before using Card Train. By registering or using our service, you agree to comply with all provisions of these terms. If you do not agree, please do not use the service.",
  "terms.footer": "These Terms of Service are established by Card Train and we reserve the right of final interpretation.",
  "terms.sections": [
    {
      "id": "service",
      "title": "Service Description",
      "content": [
        "Card Train is an online lucky bag draw platform where users can use points (CTP) to participate in various lucky bag draws.",
        "All lucky bag products on this platform are officially licensed. We guarantee that the products are legally sourced and of high quality.",
        "Users must register and log in to access full service features."
      ]
    },
    {
      "id": "points",
      "title": "Points Usage Rules",
      "content": [
        "Points (CTP) are the only currency for draws on this platform.",
        "Points can be obtained through purchase, daily check-in, friend referrals, or naked card redemption.",
        "CardTrain Points (CTP) are valid for 365 days from the date of acquisition. Expired points will be automatically forfeited and are non-refundable.",
        "Once points are used, they cannot be refunded. Please use them carefully.",
        "Points may not be transferred, sold, or exchanged for cash in any way.",
        "The platform reserves the right to adjust point acquisition methods and usage rules."
      ]
    },
    {
      "id": "draw",
      "title": "Draw Rules",
      "content": [
        "Each draw consumes the points required for the corresponding lucky bag. Draw results are generated instantly and cannot be redrawn.",
        "Draw results are randomly generated by the system. The platform does not interfere with or manipulate draw results.",
        "Open boards display the remaining prize count, while closed boards do not disclose the remaining count.",
        "Winners must fill in their shipping address within 7 days. Failure to do so will be considered a forfeiture of the prize claim.",
        "The prize content and rarity distribution of each lucky bag are subject to the product page description."
      ]
    },
    {
      "id": "prize",
      "title": "Prize Claim",
      "content": [
        "After winning, please go to the User Center to fill in a complete and correct shipping address.",
        "Prizes will be shipped within 3-5 business days after the address is confirmed.",
        "The platform is not responsible for reshipping due to incorrect address entry.",
        "No returns or exchanges are accepted after the prize is shipped, unless the product is defective or damaged.",
        "Naked card prizes can be redeemed for points. Once redeemed, the prize can no longer be claimed as a physical item."
      ]
    },
    {
      "id": "account",
      "title": "Account Rules",
      "content": [
        "Each user may only register one account. Multiple accounts are prohibited.",
        "The use of any cheats, bots, or automated programs to participate in draws is prohibited.",
        "Exploiting system vulnerabilities or using improper means to obtain points or prizes is prohibited.",
        "Violators may have their account suspended or terminated by the platform without refund of any points or prizes.",
        "Users should keep their account credentials secure. The platform is not liable for losses caused by personal negligence."
      ]
    },
    {
      "id": "disclaimer",
      "title": "Disclaimer",
      "content": [
        "The platform is not responsible for service interruptions caused by network outages, system failures, or force majeure.",
        "Prize images are for reference only. The actual product is subject to the physical item received.",
        "The platform reserves the right to modify, suspend, or terminate the service at any time without prior notice.",
        "By using this service, you agree to these Terms of Service. If you disagree, please stop using the service."
      ]
    },
    {
      "id": "modification",
      "title": "Terms Modification",
      "content": [
        "These Terms of Service may be updated from time to time. The updated terms will take effect upon posting on the website.",
        "Users are responsible for regularly reviewing the latest version of the Terms of Service.",
        "Continued use of the service constitutes acceptance of the modified terms."
      ]
    },
    {
      "id": "contact",
      "title": "Contact",
      "content": [
        "If you have any questions about these Terms of Service, please contact us through the Contact Us page.",
        "Customer Service Email: cardtrain@ct-vest.com",
        "We will respond within 1-3 business days of receiving your message."
      ]
    }
  ]
};

export default translation;